# Copyright (C) 2017 KPMG LLP, a Delaware limited liability partnership and the U.S. member firm of the KPMG network of independent member firms affiliated with KPMG International Cooperative (“KPMG International”), a Swiss entity. All rights reserved.

#https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md
is: [secured]
type:
  collection-readonly:
    collection-example: !include "order-collection.example.json"
    collection-schema: OrderCollection

/{orderId}:
  is: [secured]
  type:
    member-readonly:
      member-example: !include "order.example.json"
      member-schema: Order

/current:
  is: [secured]
  type:
    member-readonly:
      member-example: !include "order.example.json"
      member-schema: Order

/current/add-item:
    is: [secured]
    description: |
      Add to the current cart (Order with status CART)
    post:
      description: |
        Add a specific cartItem
      body:
        schema: AddToOrder
        example: !include "add-to-order.example.json"
      responses:
        200:
          body:
            schema: Order
            example: !include "order.example.json"
        409:
          description: |
            Unable to process request to do conflict in state of object. Any specific details included in body.

/current/submit-order:
    is: [secured]
    description: |
        For orders with status CART, change status to PROCESSING and make any other necessary backend updates
    post:
        description: |
            Order confirmation
        responses:
            200:
                body:
                    schema: Empty
                    example: "{}"
            409:
                description: |
                    Unable to process request to do conflict in state of object. Any specific details included in body.
