# Copyright (C) 2017 KPMG LLP, a Delaware limited liability partnership and the U.S. member firm of the KPMG network of independent member firms affiliated with KPMG International Cooperative (“KPMG International”), a Swiss entity. All rights reserved.

is: [secured]
type:
  collection-readonly:
    collection-example: !include "user-collection.example.json"
    collection-schema: UserCollection
get:
  queryParameters:
    terms:
      description: A string of terms to query for users by
      type: string
      example: ?terms=john
      required: false

/current:
  type:
    member-readonly:
      member-example: !include "user.example.json"
      member-schema: User
  is: [secured,action,member]
  description: Gets the current logged in user

/{userId}:
  type:
    member-readonly:
      member-example: !include "user.example.json"
      member-schema: User
  is: [secured]
