# Copyright (C) 2017 KPMG LLP, a Delaware limited liability partnership and the U.S. member firm of the KPMG network of independent member firms affiliated with KPMG International Cooperative (“KPMG International”), a Swiss entity. All rights reserved.

is: [secured]
type:
  collection-readonly:
    collection-example: !include "category-collection.example.json"
    collection-schema: CategoryCollection

/stats:
    is: [secured]
    type:
        collection-readonly:
            collection-example: !include "category-stats.example.json"
            collection-schema: CategoryStats
