#%RAML 0.8
title: WebStart Example Services
version: 1
baseUri: /api/v1
mediaType: application/json
protocols:
  - HTTP

documentation:
    - title: TODO
      content: Put your stuff here!

schemas:
    -
        Image: !include "api/v1/images/image.schema.json"
        ImageCollection: !include "api/v1/images/image-collection.schema.json"
        Cart: !include "api/v1/carts/cart.schema.json"
        CartCollection: !include "api/v1/carts/cart-collection.schema.json"
        Product: !include "api/v1/products/product.schema.json"
        ProductCollection: !include "api/v1/products/product-collection.schema.json"
        Empty: !include "api/v1/common/empty.schema.json"
        Error: !include "api/v1/errors/error.schema.json"
        User: !include "api/v1/users/user.schema.json"
        UserCollection: !include "api/v1/users/user-collection.schema.json"
        Login: !include "api/v1/login/login.schema.json"

securitySchemes: []

traits: !include api/traits.raml
resourceTypes: !include api/types.raml

/errors: !include api/v1/errors/errors.raml
/login: !include api/v1/login/login.raml
/users: !include api/v1/users/users.raml
#/carts: !include api/v1/carts/carts.raml
/products: !include "api/v1/products/products.raml"
#/images: !include "api/v1/images/images.raml"
