#https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md
displayName: "image"
is: [secured]
type:
  collection:
    collection-example: !include "image-collection.example.json"
    collection-schema: ImageCollection
    member-example: !include "image.example.json"
    member-schema: Image

/{imageId}:
  is: [secured]
  type:
    member:
      member-example: !include "image.example.json"
      member-schema: Image
