# Copyright (C) 2017 KPMG LLP, a Delaware limited liability partnership and the U.S. member firm of the KPMG network of independent member firms affiliated with KPMG International Cooperative (“KPMG International”), a Swiss entity. All rights reserved.

#https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md
displayName: "image"
is: [secured]
type:
  collection:
    collection-example: !include "image-collection.example.json"
    collection-schema: ImageCollection
    member-example: !include "image.example.json"
    member-schema: Image

/{imageId}:
  is: [secured]
  type:
    member:
      member-example: !include "image.example.json"
      member-schema: Image
