  #used by default in the error handler service in the preloader module
  displayName: error
  is: [mock]
  description: |
    When an error is encountered by a client, it will send diagnositc information to this service which will log the information for later analysis.
  type:
    collection-writeonly:
      member-example: !include "error.example.json"
      member-schema: Error

