#https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md
#see traits.raml for more traits: secured, paged...
is: [secured]
type:
  #see types.raml for more options: collection, collection-readonly, collection-writeonly...
  collection:
    collection-example: !include "collection.example.json"
    collection-schema: {{answers.name}}Collection
    #member properties are not used for some collection types
    member-example: !include "member.example.json"
    member-schema: {{answers.name}}

/{{leftBrace}}{{camelCase answers.name}}Id{{rightBrace}}:
  #see traits.raml for more traits: secured, paged...
  is: [secured]
  type:
    #see types.raml for more options: member, member-readonly, member-writeonly...
    member:
      member-example: !include "member.example.json"
      member-schema: {{answers.name}}
